### PR TITLE
Add Linix oneliner to download latest `tflint`

### PR DESCRIPTION
**Pull request by abitrolly**

### CODE REVIEW

**Comment by wata727** [comment]
Why we need the oneliner script? Is `install_linux.sh` not enough?
I think it would be better to keep the README as simple as possible...

**Comment by abitrolly** [comment]
Onliner has an advantage that it can be copy-pasted into terminal and recorded in shell history in case the program needs to be updated again. With `install_linux.sh` I need to keep it around or download every time.

**Comment by wata727** [comment]
OK, it makes sense. How about the following oneliner script instead?

```sh
$ curl https://raw.githubusercontent.com/wata727/tflint/master/install_linux.sh | sh
```

**Comment by abitrolly** [comment]
I personally still prefer to understand what a script does. Nevertheless that's also a good solution for my user story.

**Comment by wata727** [comment]
I personally prefer not this oneliner, but I respect your opinion. If we get any other feedback, I will reconsider it again.

**Comment by wata727** [comment]
I personally prefer not this oneliner, but I respect your opinion. If we get any other feedback, I will reconsider it again.

**Pull request merged**
