### PR TITLE
Improve TFLint 🚀 

### PR DESCRIPTION
**Pull request by wata727**
Fixes https://github.com/wata727/tflint/issues/179

This pull request changes the internal system drastically by embedding Terraform as a library. Therefore, some breaking changes are included, please see the following for details.

**NOTE: This changelog may be changed later because it is draft.**

## Breaking Changes 🔥 
- Always return an error when failed to evaluate an expression #211 
  - Until now, except for module attributes, even if an error occurred, it was ignored.
  - However, expressions including unsupported syntax (such as `${module.foo}`) are not evaluated, so no error occurs.
- Drop support for `${terraform.env}` #211 
  - Previously `${terraform.env}` was a valid expression that returned the same as `${terraform.workspace}`.
  - This is because Terraform v0.12 doesn't support `${terraform.env}`.
- The file name of a module includes module ID instead of the `source` attribute #211 
  - Up to now it was output like `github.com/wata727/example-module/instance.tf`, but it will be changed like `module_id/instance.tf`.
- Always parse all configuration files under the current directory #229 #232 
  - When passing a file name as an argument, TFLint only parsed that file so far, but it now parses all configuration files under the current directory.
  - Also, file arguments are only used to filter the issues obtained. Therefore, you cannot specify files other than under the current directory.
  - As a known issue, If file arguments are specified, module's issues are not reported. This will be improved by changing handling of module's issues in the future.
  - These behaviors have been changed as it depends on Terraform's `configload` package.
  - In addition, modules are always loaded regardless of `ignore_module`.
- Raise an error when using invalid syntax as the Terraform configuration #217 
  - For example, it didn't raise an error when using `resources`(not `resource`) block because it is valid as HCL syntax in previous versions. 
- Remove `--debug` option #223 
  - Please use `TFLINT_LOG` environment variables instead.
- Raise an error when the file specified by `--config` does not exist #224 
  - Previously the error was ignored and the default config was referenced.
- Remove duplicate resource rules #227 
  - This is due to technical difficulty and user experience.

## Enhancements 💪 
- Support new HCL syntax #211
  - See also: https://www.hashicorp.com/blog/terraform-0-1-2-preview
- Support built-in functions #211 
  - Until now, if an expression includes function, it was ignored.
- `TF_DATA_DIR` and `TF_WORKSPACE` environment variables are now available #211 
  - Until now, these variables are ignored.
- It is now possible to handle values doesn't have a default without raising errors #211 #220 
  - In the past, an error occurred when there was a reference to a variable that had no default value in an attribute of a module. See #205 
- Support Terraform v0.11 modules #217 
  - Until now, it is failed to properly load a part of Terraform v0.11 module. See also #167 
- Support for automatic loading `*.auto.tfvars` files #228 
  - Previously it was not loaded automatically.

## BugFixes 🙇 
- Improve expression checks #211 
  - Since it used to be checked by a regular expression, there were many bugs, but it was greatly improved by using the `terraform/lang` package. See #204 #160 
- Stop overwriting the config under the current directory by the config under the homedir #224 
  - Fixed the problem that overwrites the config under the current directory by homedir config.
- Improve to check for `aws_db_instance_readable_password` #233 
  - Previously, false positive occurred when setting values files or environment variables, but this problem has been fixed.

# ToDo

- [x] Introduce `Runner` that use `terraform.BuiltinEvalContext`
  - #211 #227 #228 #232 
- [x] Re-implement each detectors without `reflect` package
  - #230 #233 #235 #238 #239 #240 #242 #246 
- [x] Re-implement loader with Terraform's `configload` package
  - #217 
- [x] Handle resources and modules with Terraform's `configs` package
  - #219 #220 #223  #224 #229 
- [x] Test Terraform behavior
  - [x] Multiple block declaration. See #238 
  - [x] Map variable merging. See #241

### CODE REVIEW

**Comment by yardensachs** [comment]
👌

**Comment by hoeg** [comment]
Any idea about when this is going to be merged?

**Comment by wata727** [comment]
@hoeg All tasks are already finished. However, these features depend on **unstable** version of Terraform v0.12. Thus, I can't merge this pull request until stable version is released...

**Comment by howdoicomputer** [comment]
https://www.hashicorp.com/blog/announcing-terraform-0-1-2-beta1

**Pull request merged**
