### PR TITLE
Update aws-sdk and terraform

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by wata727** [comment]
Thank you @chenrui333, but CI has failed.

When upgrading aws-sdk-go, run `make code` to regenerate the mocks.
https://github.com/wata727/tflint/pull/506/checks?check_run_id=283998224#step:4:135

**Comment by chenrui333** [comment]
Thanks for the tip, doing it now.

**Comment by chenrui333** [comment]
@wata727 it works now. Thanks!

**Comment by wata727** [comment]
👍

**Pull request merged**
