### PR TITLE
Update dependencies to Terraform 0.12.6

### LINKED ISSUE #374: tflint 0.9.2 issue with terraform 0.12.6, for_each
tflint                                                                                                                                                       
Error: Failed to load configurations: main.tf:42,3-11: Reserved argument name in resource block; The name "for_each" is reserved for use in a future version of Terraform.

This is implemented now in tf 0.12.6

### PR DESCRIPTION
**Pull request by lawliet89**
Fixes #374

I had to edit the generated `tflint/loader_mock.go` because it was creating a circular dependency.

### CODE REVIEW

**Comment by wata727** [comment]
> I had to edit the generated tflint/loader_mock.go because it was creating a circular dependency.

Does that circular dependency fail the test?
In my environment, it seems that I can pass the test without any changes.

```
$ GO111MODULE=on make code
go mod vendor
go generate ./...
$ GO111MODULE=on make test
go mod vendor                                                                                                   
go test $(go list ./... | grep -v vendor | grep -v aws-sdk-go)                                                  
ok      github.com/wata727/tflint       0.117s                                                                  
ok      github.com/wata727/tflint/client        0.014s                                                          
ok      github.com/wata727/tflint/cmd   0.078s
ok      github.com/wata727/tflint/issue 0.027s [no tests to run]
ok      github.com/wata727/tflint/printer       0.036s
?       github.com/wata727/tflint/project       [no test files]
ok      github.com/wata727/tflint/rules 0.033s
ok      github.com/wata727/tflint/rules/awsrules        0.100s
ok      github.com/wata727/tflint/rules/awsrules/models 0.118s
ok      github.com/wata727/tflint/rules/terraformrules  0.015s
ok      github.com/wata727/tflint/tflint        0.098s
```

**Comment by lawliet89** [comment]
If I run `make code` again, it creates the diff

```diff
diff --git a/tflint/loader_mock.go b/tflint/loader_mock.go
index f479e4c..a8796a5 100644
--- a/tflint/loader_mock.go
+++ b/tflint/loader_mock.go
@@ -8,6 +8,7 @@ import (
        gomock "github.com/golang/mock/gomock"
        configs "github.com/hashicorp/terraform/configs"
        terraform "github.com/hashicorp/terraform/terraform"
+       tflint "github.com/wata727/tflint/tflint"
        reflect "reflect"
 )
 
@@ -50,10 +51,10 @@ func (mr *MockAbstractLoaderMockRecorder) LoadConfig(arg0 interface{}) *gomock.C
 }
 
 // LoadAnnotations mocks base method
-func (m *MockAbstractLoader) LoadAnnotations(arg0 string) (map[string]Annotations, error) {
+func (m *MockAbstractLoader) LoadAnnotations(arg0 string) (map[string]tflint.Annotations, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "LoadAnnotations", arg0)
-       ret0, _ := ret[0].(map[string]Annotations)
+       ret0, _ := ret[0].(map[string]tflint.Annotations)
        ret1, _ := ret[1].(error)
        return ret0, ret1
 }
```

and it fails to build:

```
$ make 
go mod vendor
go test $(go list ./... | grep -v vendor | grep -v aws-sdk-go)
can't load package: import cycle not allowed
package github.com/wata727/tflint
	imports github.com/wata727/tflint/cmd
	imports github.com/wata727/tflint/rules
	imports github.com/wata727/tflint/rules/awsrules
	imports github.com/wata727/tflint/tflint
	imports github.com/wata727/tflint/tflint
import cycle not allowed
package github.com/wata727/tflint
	imports github.com/wata727/tflint/cmd
	imports github.com/wata727/tflint/rules
	imports github.com/wata727/tflint/rules/awsrules
	imports github.com/wata727/tflint/tflint
	imports github.com/wata727/tflint/tflint
make: *** [Makefile:7: test] Error 1

```

**Comment by wata727** [comment]
That's strange. There may be a problem with the versions of mockgen and Go. Can you update the mockgen to the latest?

My environment:

```
$ go version
go version go1.12 linux/amd64
$ cd $GOPATH/src/github.com/golang/mock
$ git rev-parse HEAD
6e20fef50e74e443696bc32b693cf286b612d45b
```

**Comment by lawliet89** [comment]
```
yongwen@yongwen-thinkpad:~/go/src/github.com/golang/mock (master=)$ go version
go version go1.12.5 linux/amd64
yongwen@yongwen-thinkpad:~/go/src/github.com/golang/mock (master=)$ git rev-parse HEAD
dd8d2a22370e4c8a334e80ca8477f71356c8e4bb
yongwen@yongwen-thinkpad:~/go/src/github.com/golang/mock (master=)$ git pull
Already up to date.
```

This is the latest.

**Comment by wata727** [comment]
Ah, ok. My gomock seems to be old.
By the way, there is still no diff when running `make code`, how is that? 

```
$GO111MODULE=on make code
go mod vendor
go generate ./...
$ git diff
(no stdout)
```

```
$ git rev-parse HEAD
dd8d2a22370e4c8a334e80ca8477f71356c8e4bb
```

**Comment by lawliet89** [comment]
I found out why. If I check out `tflint` inside `$GOPATH` and I run `$GO111MODULE=on make code`, then there is no diff and it works fine.

**Pull request merged**
